<?php
/* 
 * Authod       Tony Vu
 * Date         12.12.2013
 * Description  Css Config from backend theme
 */
?>
<?php
    /* full grid layout */
	$fullgrid_header_bgcolor = '#' . Mage::getStoreConfig('setting/pagebg/fullgrid_header', Mage::app()->getStore()->getId());
	$fullgrid_footer_bgcolor = '#' . Mage::getStoreConfig('setting/pagebg/fullgrid_footer', Mage::app()->getStore()->getId());
	$fullgrid_footer_main_container = '#' . Mage::getStoreConfig('setting/pagebg/fullgrid_main_container', Mage::app()->getStore()->getId());
    
    /* theme font */
    $fontfm = Mage::getStoreConfig('setting/themefont/fontfamily', Mage::app()->getStore()->getId());
    // if $fontsize == null then fontsize is 14px from bootstrap theme
    $fontsize = Mage::getStoreConfig('setting/themefont/fontsize', Mage::app()->getStore()->getId());
    $textcolor = '#' . Mage::getStoreConfig('setting/themefont/textcolor', Mage::app()->getStore()->getId());
    
    /* header */
    $header_link_color = '#' . Mage::getStoreConfig('setting/header/link_color', Mage::app()->getStore()->getId());
    $header_link_size = Mage::getStoreConfig('setting/header/link_size', Mage::app()->getStore()->getId());
    $header_hoverlink_color = '#' . Mage::getStoreConfig('setting/header/hoverlink_color', Mage::app()->getStore()->getId());
    $header_hoverlink_size = Mage::getStoreConfig('setting/header/hoverlink_size', Mage::app()->getStore()->getId());
    
    /* footer */
    $footer_link_color = '#' . Mage::getStoreConfig('setting/footer/link_color', Mage::app()->getStore()->getId());
    $footer_link_size = Mage::getStoreConfig('setting/footer/link_size', Mage::app()->getStore()->getId());
    
    // get default size 
    if ($footer_link_size == ''){
        $footer_link_size = $fontsize;
    }
    
    $footer_title_color = '#' . Mage::getStoreConfig('setting/footer/title_color', Mage::app()->getStore()->getId());
    $footer_title_size = Mage::getStoreConfig('setting/footer/title_size', Mage::app()->getStore()->getId());
    // get default size 
    if ($footer_title_size == ''){
        $footer_title_size = $fontsize;
    }
    
    $footer_text_color = '#' . Mage::getStoreConfig('setting/footer/text_color', Mage::app()->getStore()->getId());
    $footer_text_size = Mage::getStoreConfig('setting/footer/text_size', Mage::app()->getStore()->getId());
    // get default size 
    if ($footer_text_size == ''){
        $footer_text_size = $fontsize;
    }
    
?>

<style type="text/css">
    
body{font-family: <?php echo $fontfm ?>; font-size:<?php echo $fontsize ?>; color: <?php echo $textcolor ?>; text-align:center}
.fullgrid-header{margin: 0 auto; background: <?php echo $fullgrid_header_bgcolor?>}
.fullgrid-footer{margin: 0 auto; background: <?php echo $fullgrid_footer_bgcolor?>}
.header{padding: 10px 0px;}
.header .links a { color:<?php echo $header_link_color ?>; font-size: <?php echo $header_link_size ?>;}
.header .links a:hover { color:<?php echo $header_hoverlink_color ?>; font-size: <?php echo $header_hoverlink_size ?>;}
.header .links .top-link-cart i{margin-left: 5px;}
.navbar-header .navbar-brand{text-transform: uppercase}
.fullgrid-main-container {background:<?php echo $fullgrid_footer_main_container; ?>; margin: 0 auto; padding: 20px 0 40px}
.footer {color:<?php echo $footer_text_color ?>; font-size: <?php echo $footer_text_size ?>; text-align:left}
.footer a { color:<?php echo $footer_link_color ?>; text-decoration:none; font-size: <?php echo $footer_link_size ?>}
.footer .title{color:<?php echo $footer_title_color ?>; font-size: <?php echo $footer_title_size ?>; text-transform: uppercase; padding: 2px 0}
.footer address a { color:<?php echo $footer_link_color ?>; text-decoration:underline; font-size: <?php echo $footer_link_size ?>}

.product-options .options-list label { font-weight:normal; color: <?php echo $textcolor?>; font-size:11px}
</style>
    
