<?php
/* 
 * Authod       Tony Vu
 * Date         24.12.2013
 * Description  Mega Menu 
 */
?>

<?php        
    // get storeconfig
     $is_Megamenu = Mage::getStoreConfig('yamm/setting/yes_no', Mage::app()->getStore()->getId());
     // if Megamenu is yes
     if($is_Megamenu  == 1){ 
        $narbar_style = Mage::getStoreConfig('yamm/setting/navbar', Mage::app()->getStore()->getId()); 
        if ($narbar_style ==''){
           // navbar-default is an option in the setting/header/navbar
           $narbar_style = 'navbar-default';
        }    
      
?>

<div class="navbar yamm <?php echo $narbar_style ?>">
    <div class="container">
      <div class="navbar-header">
        <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <!-- company logo -->
        <a href="#" class="navbar-brand">Menu</a>
      </div>
      <div id="navbar-collapse-1" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <!-- fist menu item -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo Mage::getStoreConfig('yamm/first_menu_item/title', Mage::app()->getStore()->getId()) ?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <!-- Content container to add padding -->
                <div class="yamm-categories yamm-content megamenu_cat_1">
                 <!-- banner for promotion -->          
                 <?php if(Mage::getStoreConfig('yamm/first_menu_item/ad', Mage::app()->getStore()->getId()) != null): ?>
                    <div class="row">
                        <a href="<?php echo Mage::getStoreConfig('yamm/first_menu_item/link', Mage::app()->getStore()->getId()) ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'ad_banner/' . Mage::getStoreConfig('yamm/first_menu_item/ad', Mage::app()->getStore()->getId()); ?>" class="img-responsive" alt="<?php echo Mage::getStoreConfig('yamm/first_menu_item/alt', Mage::app()->getStore()->getId()) ?>"></a>
                    </div>
                 <?php endif; ?>
                 <?php 
                    // back end config 
                    $subcat = Mage::getStoreConfig('yamm/first_menu_item/catid', Mage::app()->getStore()->getId());
                    
                    $categories = Mage::helper('mega/data')->getCatergorybyLevel($subcat);    
                    echo $categories;
                 ?>

                </div>
              </li>
            </ul>
          </li>
          <!-- Second Menu Item -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><?php echo Mage::getStoreConfig('yamm/second_menu_item/title', Mage::app()->getStore()->getId()) ?><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <div class="yamm-content megamenu_cat_2">                                
                    <?php 
                        $catid = Mage::getStoreConfig('yamm/second_menu_item/catid', Mage::app()->getStore()->getId());
                        //echo $catid;
                        $featured_category = Mage::helper('mega/data')->getFeaturedCategory($catid);    
                        echo $featured_category;
                    ?>
                </div>
              </li>
            </ul>
          </li>           
          <!-- Sales -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Sales<b class="caret"></b></a>              
                <ul class="dropdown-menu">
                  <li>
                    <div class="megamenu_cat_3 col-xs-12"> 
                        <div class='row'>
                            <?php if(Mage::getStoreConfig('yamm/sale/ad') != null): ?>
                                <div class='col-sm-12 banner'>
                                    <a href="<?php echo Mage::getStoreConfig('yamm/sale/link', Mage::app()->getStore()->getId()) ?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'ad_banner/' . Mage::getStoreConfig('yamm/sale/ad'); ?>" class="img-responsive" alt="<?php echo Mage::getStoreConfig('yamm/sale/alt') ?>"></a>
                                </div>
                            <?php endif; ?>
                            <div class='col-sm-12'>
                                <?php 
                                    //get feature products from getstoreconfig
                                      $product_arr = unserialize(Mage::getStoreConfig('yamm/sale/product', Mage::app()->getStore()->getId()));
                                        if (!empty($product_arr)){
                                            $product_sale_list = array();
                                            foreach($product_arr as $product){
                                                array_push($product_sale_list ,trim($product['product_sku']));
                                            }
                                            echo Mage::helper('mega/data')->getSaleProducts($product_sale_list);
                                        }                              
                                ?>
                            </div>
                        </div>
                    </div>
                  </li>
                </ul>
        </li>
      </div>
    </div>
</div>

<script type='text/javascript' defer>        
    jQuery('.yamm .dropdown-menu').click(function(e) {
       e.stopPropagation();
     });
 </script>
 
 <?php } ?>